# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rd_t6aWkAnob2XwLo9z55KPJzl9EEHZE
"""

import pandas as pd
df=  pd.DataFrame({ 'Name': ['Zulayho', 'Nigora' ,'Sarvinoz','muhammmadjon','ali','boynazar','nurulloh'],

                              'Surname': ['Kadamova', 'Yusupova', 'Tokhirova','xonqulov','boymirzayev','toxtasinov','aminjonov'],

                                'Age': ['28', '17', '30','19','19','19','19'],

                                'Course': ['4', '2', '7','2','2','2','2']


})

print(df)

df.to_excel('report.xlsx', index=False, sheet_name='Sheet1')